services:
  agent-validator:
    image: redteamsubnet61/agent-validator:2.2.2-260226
    build:
      context: .
    restart: unless-stopped
    environment:
      TERM: ${TERM:-xterm}
      TZ: ${TZ:-UTC}
      RT_BTCLI_WALLET_DIR: "${RT_BTCLI_WALLET_DIR:?error}"
      RT_VALIDATOR_WALLET_NAME: ${RT_VALIDATOR_WALLET_NAME:?error}
      RT_VALIDATOR_HOTKEY_NAME: ${RT_VALIDATOR_HOTKEY_NAME:?error}
    env_file:
      - path: .env
        required: false
    labels:
      - 'wud.tag.transform=^(\d+\.\d+\.\d+)-\d{6}$ => $1'
      - 'wud.tag.include=^\d+\.\d+\.\d+-\d{6}$'
      - 'wud.tag.exclude=^latest$'
      - "wud.display.name=Agent Validator"
      - "wud.watch=true"
    volumes:
      - "${RT_BTCLI_WALLET_DIR:?error}:${RT_BTCLI_WALLET_DIR:?error}"
      - "./volumes/storage/agent-validator/logs:/var/log/agent-validator"
      - "./volumes/storage/agent-validator/data:/var/lib/agent-validator"
    network_mode: "host"
    tty: true
  wud:
    image: getwud/wud:8.1.1
    container_name: wud
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./volumes/storage/wud/data:/store"
    environment:
      TERM: ${TERM:-xterm}
      TZ: ${TZ:-UTC}
      WUD_WATCHER_LOCAL_WATCHBYDEFAULT: false
      WUD_WATCHER_LOCAL_SOCKET: "/var/run/docker.sock"
      WUD_WATCHER_LOCAL_WATCHATSTART: true
      WUD_WATCHER_LOCAL_CRON: "10 * * * *"
      WUD_TRIGGER_DOCKER_LOCAL_AUTO: true
      WUD_TRIGGER_DOCKER_LOCAL_DRYRUN: false
      WUD_TRIGGER_DOCKER_LOCAL_PRUNE: true
      WUD_TRIGGER_DOCKER_LOCAL_THRESHOLD: minor
    tty: true
