services:
  agent-validator:
    image: redteamsubnet61/agent-validator:2.0.0-251224
    build:
      context: .
    restart: unless-stopped
    environment:
      TERM: ${TERM:-xterm}
      TZ: ${TZ:-UTC}
      RT_BTCLI_WALLET_DIR: "${RT_BTCLI_WALLET_DIR}"
      RT_VALIDATOR_WALLET_NAME: ${RT_VALIDATOR_WALLET_NAME}
      RT_VALIDATOR_HOTKEY_NAME: ${RT_VALIDATOR_HOTKEY_NAME}
    env_file:
      - path: .env
        required: false
    volumes:
      - "${RT_BTCLI_WALLET_DIR}:${RT_BTCLI_WALLET_DIR}"
      - "./volumes/storage/agent-validator/logs:${RT_VALIDATOR_LOGS_DIR:-/var/log/agent-validator}"
      - "./volumes/storage/agent-validator/data:${RT_VALIDATOR_DATA_DIR:-/var/lib/agent-validator}"
    tty: true
